name: Security Scan

on:
  push
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # CONFIG
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Config docker
        uses: docker/setup-buildx-action@v1

      # RUN APP
      - name: Run api server
        run: docker run -d --publish 5000:5000 frolvlad/flask-restplus-server-example
      
      # DAST
      - name: Owasp ZAP (DAST)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://127.0.0.1:5000'