name: Security Scan

on:
  push
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
     
      - name: Config docker
        uses: docker/setup-buildx-action@v1

      - name: Run api server
        run: docker run -d --publish 5000:5000 frolvlad/flask-restplus-server-example
      
      - name: Run owasp zap (dast)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://127.0.0.1:5000'

  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:

      # step 1
      - name: clone application source code
        uses: actions/checkout@v3

      # step 2
      - name: full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      # step 3
      
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif
          
      # step 4
      - name: Download report
        uses: actions/download-artifact@v2
        with: 
          name: report.sarif